Feature/modules
tvivls/02-npm-modules pull request #1
Opened 2023-07-02 14:37 UTC by tvivls

2023-07-02 14:40 UTC, tvivls commented
@heyanniemoran

2023-07-03 11:20 UTC, heyanniemoran requested changes

2023-07-03 11:20 UTC, heyanniemoran commented on react-document-visibility/src/hooks/useDocumentVisibility.ts
> +import {useEffect, useState} from 'react';
1. Не улавливает, что вкладка неактивна
2. Не всегда обновляет, что покинули страницу. То через раз обновляет, то через 3 раза обновляет.
3. Крашится, если раза 10 туда-сюда с вкладки на вкладку бегаю.

2023-07-03 11:20 UTC, heyanniemoran commented on react-document-visibility/src/hooks/useDocumentVisibility.ts
> +    const [visible, setVisible] = useState(true);
Если я открою вкладку, но не зайду на нее, то у меня всё равно изначально visible будет true.

2023-07-03 11:20 UTC, heyanniemoran commented on react-document-visibility/src/hooks/useDocumentVisibility.ts
> +        onVisibilityChange: (callback: EventListener) => {
Лучше вынести функцию, плохо читается.

2023-07-03 11:20 UTC, heyanniemoran commented on react-document-visibility/src/hooks/useDocumentVisibility.ts
> +    }, []);
Просто общее по стилю кода - лучше блоки разделять.
`const handleVisibility = () => { ... }`
пустая строка
`useEffect(() => { ... }, [ ... ])`
пустая строка
`return ( ... )`

2023-07-03 11:20 UTC, heyanniemoran commented on react-document-visibility/tsconfig.json
> +    /* Visit https://aka.ms/tsconfig to read more about this file */
И нужны тебе эти комменты?

2023-07-03 11:20 UTC, heyanniemoran commented on react-responsive/src/components/MediaQuery.tsx
> +                : (matches && <div>{children}</div>)}
react fragment вместо div

2023-07-04 12:48 UTC, tvivls commented
@heyanniemoran

2023-07-04 14:51 UTC, heyanniemoran commented
Плюсом:
1. Надо, чтобы поддерживались версии реакта от 16.8.0
2. Если у тебя есть повторяющиеся части - их лучше вынести. Например, повторяющиеся типы.

2023-07-06 12:20 UTC, tvivls commented
@heyanniemoran

2023-07-07 12:32 UTC, heyanniemoran commented on react-document-visibility/src/hooks/useDocumentVisibility.ts
> +  const [visible, setVisible] = useState<boolean>(documentVisibility);
1. Не всегда необходимо указывать тип `(): boolean`, `(): void`. Посмотри где можно убрать, а где оставить.
2. Можно сразу прокинуть `document.visibilityState === 'visible'`. Если что-то можно прокинуть сразу без переменной, то лучше так сделать.

2023-07-07 12:33 UTC, heyanniemoran commented on react-responsive/src/components/MediaQuery.tsx
> +export type ResolutionType = `${number}dppx` | number;
Ты его никуда не экспортишь

2023-07-07 12:35 UTC, heyanniemoran commented on react-responsive/src/components/MediaQuery.tsx
> +  const mediaQuery: string[] = Object.entries(props).map(([key, value]) => {
Давай вынесем функцию из компонента. Подумай как лучше всего это сделать.

2023-07-07 12:36 UTC, heyanniemoran commented on react-responsive/src/hooks/useMediaQuery.ts
> +    const [matches, setMatches] = useState(false);
1. Давай прокидывать сразу значение, которое будет.
2. Давай добавим поддержку ssr.

2023-07-07 12:38 UTC, heyanniemoran commented on react-responsive/src/components/MediaQuery.tsx
> +export type QueryProps = {
Давай доработаем так, чтобы пользователь обязательно прокинул хотя бы один проп.

2023-07-08 13:32 UTC, tvivls commented
@heyanniemoran

2023-07-08 14:32 UTC, heyanniemoran commented on react-responsive/src/components/MediaQuery.tsx
> +    .join(' and ');
Почти. Я бы предложила вынести всю логику в функцию.

2023-07-08 14:32 UTC, heyanniemoran commented on react-responsive/src/hooks/useMediaQuery.ts
> +    } else throw new Error('Медиа-запрос не может быть вполнен');
Почему бы не давать использовать этот пакет с ssr?

2023-07-10 08:12 UTC, tvivls commented
@heyanniemoran

2023-07-28 14:22 UTC, merged